version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  webserver:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
